---
apiVersion: v1
data:
  password: VHhWZVE0bk44MlNTaVlIb3N3cU9VUlp2UURhTDRLcE5FbHNDRUVlOWJ3RHhNZDczS2NrSWVYelM1Y1U2TGlDMg==
  username: YXBw
kind: Secret
metadata:
  name: ikenna-apicurio-user
type: kubernetes.io/basic-auth
---
apiVersion: v1
data:
  password: dU4zaTFIaDBiWWJDYzRUeVZBYWNCaG1TemdxdHpxeG1PVmpBbjBRSUNoc0pyU211OVBZMmZ3MnE4RUtLTHBaOQ==
  username: cG9zdGdyZXM=
kind: Secret
metadata:
  name: ikenna-apicurio-superuser
type: kubernetes.io/basic-auth
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: ikenna-apicurio-cluster
spec:
  description: "Pg cluster apicurio"
  imageName: ghcr.io/cloudnative-pg/postgresql:15.4
  instances: 3
  startDelay: 300
  stopDelay: 300
  primaryUpdateStrategy: unsupervised

  postgresql:
    parameters:
      shared_buffers: 256MB

  bootstrap:
    initdb:
      database: apicurio
      owner: apicurio
      secret:
        name: ikenna-apicurio-user

  superuserSecret:
    name: ikenna-apicurio-superuser

  storage:
    storageClass: gp2
    size: 1Gi