apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apicurio-registry
  namespace: argocd
spec:
  project: default
  source:
    path: helm/apicurio-registry
    repoURL: "https://github.com/qdnqn/eks-traefik-hub-argocd.git"
    targetRevision: main
    helm:
      releaseName: apicurio-registry
      valueFiles:
        - values.yaml
  destination:
    name: in-cluster
    namespace: apicurio-registry-operator-namespace
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true