apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mock
  namespace: argocd
spec:
  project: default
  source:
    path: helm/mock
    repoURL: "https://github.com/qdnqn/eks-traefik-hub-argocd.git"
    targetRevision: main
    helm:
      releaseName: mock
      valueFiles:
        - values.yaml
  destination:
    name: in-cluster
    namespace: mock
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true