apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik-configuration
  namespace: argocd
spec:
  project: default
  source:
    path: helm/traefik-configuration
    repoURL: "https://github.com/qdnqn/eks-traefik-hub-argocd.git"
    targetRevision: main
    helm:
      releaseName: traefik-configuration
      valueFiles:
        - values.yaml
  destination:
    name: in-cluster
    namespace: traefik
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true