apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
spec:
  project: default
  source:
    path: helm/prometheus
    repoURL: "https://github.com/qdnqn/eks-traefik-hub-argocd.git"
    targetRevision: main
    helm:
      releaseName: prometheus
      valueFiles:
        - values.yaml
  destination:
    name: in-cluster
    namespace: monitoring
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true