apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: ikenna-http
  namespace: apicurio-registry-operator-namespace
spec:
  acme:
    email: user@example.com
    # We use the staging server here for testing to avoid hitting
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      # if not existing, it will register a new account and stores it
      name: ikenna-dev
    solvers:
      - http01:
          # The ingressClass used to create the necessary ingress routes
          ingress:
            class: traefik